name: docs
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - pip
  - openff-qcsubmit
  - openff-toolkit
  - openff-qcsubmit
  - numpy>=1.16
  - pandas
  - matplotlib
  - numpydoc
  - nbsphinx
  - jupyter_client
  - notebook
  - nbconvert
  - ipykernel
  - autodoc-pydantic
  - myst-parser~=1.0
  - pandoc
  - wheel
  - sphinx-autobuild
  - sphinx>=6.2.1,<7
  - pip:
    - readthedocs-sphinx-search
    - git+https://github.com/Yoshanuikabundi/MyST-NB.git@upgrade-to-1

