name: docs
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - pip
  - openff-qcsubmit
  - openff-toolkit
  - openff-qcsubmit
  - numpy>=1.16
  - pandas
  - matplotlib
  - numpydoc
  - nbsphinx
  - jupyter_client
  - notebook
  - nbconvert
  - ipykernel
  - autodoc-pydantic
  - myst-parser>=0.13.6
  - myst-nb
  - pandoc
  - wheel

